import { describe, it, expect, vi } from 'vitest'
import { createSearchPresetStore, readSearchPreset, copySearchPresetFilters, applySearchPresetFilters, SEARCH_PRESET_PREFIX, MAX_SEARCH_PRESETS } from './searchPresets'
const base = () => ({ query: '关关', folderId: 'p', source: 'body', days: '7', pinned: false, matchCase: true, sort: 'updated', since: 1, page: 9, revision: 'old', content: 'not stored' })
function fixture() {
 const values = new Map(); const storage = { get length() { return values.size }, key: i => [...values.keys()][i], getItem: key => values.has(key) ? values.get(key) : null, setItem: (key, value) => values.set(key, value), removeItem: key => values.delete(key) }
 let serial = 0; let time = new Date('2026-09-23T12:00:00.000Z')
 const store = createSearchPresetStore({ storage: () => storage, createId: () => 'preset-' + (++serial), now: () => time })
 return { values, storage, store, time: value => { time = new Date(value) } }
}
describe('explicit saved searches', () => {
 it('reading and normalizing never writes automatic history', () => { const { store, values } = fixture(); store.list(); copySearchPresetFilters(base()); expect(values.size).toBe(0) })
 it('keeps only approved filters, never page, revision, timestamps, result IDs or body', () => { const clean = copySearchPresetFilters(base()); expect(Object.keys(clean)).toEqual(['query','source','folderId','days','pinned','matchCase','sort']); expect(Object.isFrozen(clean)).toBe(true) })
 it('normalizes Unicode and literal query punctuation without evaluating it', () => { expect(copySearchPresetFilters({ ...base(), query:'  E\u0301LODIE <tag> A+B  ' }).query).toBe('ÉLODIE <tag> A+B') })
 it('allows browsing presets with no keyword', () => { expect(copySearchPresetFilters({ ...base(), query: '' }).query).toBe('') })
 it('rejects malformed filters and unsupported enums', () => { for (const p of [null, [], {}, { ...base(), source:'fts' }, { ...base(), days:7 }, { ...base(), sort:'unknown' }, { ...base(), pinned:'yes' }, { ...base(), matchCase:1 }, { ...base(), folderId: {} }]) expect(() => copySearchPresetFilters(p)).toThrow() })
 it('accepts exact Unicode query length but rejects oversize without truncation', () => { expect(copySearchPresetFilters({ ...base(), query: '😀'.repeat(128) }).query).toHaveLength(256); expect(() => copySearchPresetFilters({ ...base(), query: '😀'.repeat(129) })).toThrow() })
 it('saves independent records that survive a fresh store instance', () => { const f = fixture(); f.store.save('first',base()); const other = createSearchPresetStore({ storage: () => f.storage }); expect(other.list().entries[0].preset.name).toBe('first') })
 it('does not overwrite presets with the same name', () => { const f=fixture();f.store.save('same',base());f.store.save('same',{...base(),query:'other'});expect(f.store.list().entries).toHaveLength(2) })
 it('validates names and refuses empty names before writing', () => { const f=fixture(); for (const name of ['', ' ', '名'.repeat(49), {}, null]) expect(()=>f.store.save(name,base())).toThrow(); expect(f.values.size).toBe(0) })
 it('recalculates rolling dates at application time and discards old page tokens', () => { const f=fixture();f.store.save('week',base());f.time('2026-10-23T12:00:00.000Z');const view=f.store.apply(f.store.list().entries[0]);expect(view.since).toBe(Date.parse('2026-10-16T12:00:00.000Z')/1000);expect(view.page).toBe(1);expect(view.revision).toBe('') })
 it('all time stays all time, validates supplied clock and keeps directory identity', () => { expect(applySearchPresetFilters({...base(),days:'0'},1)).toMatchObject({since:0,folderId:'p'});expect(()=>applySearchPresetFilters(base(),NaN)).toThrow() })
 it('reports blocked storage instead of no saved searches', () => { const f=createSearchPresetStore({ storage:()=>{throw Error('blocked')} });expect(f.list().error).not.toBe('');expect(()=>f.save('safe',base())).toThrow() })
 it('quota errors leave old presets and unrelated keys intact', () => { const f=fixture();f.store.save('old',base());f.values.set('theme','dark');const previous=[...f.values];f.storage.setItem=()=>{throw Error('quota')};expect(()=>f.store.save('new',base())).toThrow('保存失败');expect([...f.values]).toEqual(previous) })
 it('rejects ID collisions and does not overwrite', () => { const f=fixture();f.store.save('old',base());const raw=f.values.get(SEARCH_PRESET_PREFIX+'preset-1');const other=createSearchPresetStore({storage:()=>f.storage,createId:()=> 'preset-1'});expect(()=>other.save('new',base())).toThrow('冲突');expect(f.values.get(SEARCH_PRESET_PREFIX+'preset-1')).toBe(raw) })
 it('capacity includes corrupt entries, never auto evicts', () => { const f=fixture();for(let i=0;i<MAX_SEARCH_PRESETS;i++)f.values.set(SEARCH_PRESET_PREFIX+i,'broken');expect(()=>f.store.save('next',base())).toThrow('40');expect(f.values.size).toBe(MAX_SEARCH_PRESETS) })
 it('keeps corrupt and future-version records visible but unappliable', () => { const f=fixture();f.values.set(SEARCH_PRESET_PREFIX+'bad','oops');f.store.save('valid',base());const rows=f.store.list().entries;expect(rows).toHaveLength(2);const bad=rows.find(e=>!e.preset);expect(()=>f.store.apply(bad)).toThrow();expect(f.values.has(bad.key)).toBe(true) })
 it('rejects record identity mismatch without hiding it', () => { const f=fixture();f.store.save('valid',base());const raw=f.store.list().entries[0].raw;f.values.set(SEARCH_PRESET_PREFIX+'another',raw);expect(f.store.list().entries.filter(e=>e.error)).toHaveLength(1) })
 it('validates version, dates, large data and malformed JSON', () => { const f=fixture();f.store.save('valid',base());const v=JSON.parse(f.store.list().entries[0].raw);for(const x of [{...v,version:2},{...v,savedAt:'not date'},{...v,id:'../wrong'},{...v,format:'wrong'}])expect(()=>readSearchPreset(JSON.stringify(x))).toThrow();expect(()=>readSearchPreset('x'.repeat(8193))).toThrow();expect(()=>readSearchPreset('broken')).toThrow() })
 it('stale apply and stale delete are refused', () => { const f=fixture();f.store.save('valid',base());const e=f.store.list().entries[0];f.values.set(e.key,e.raw+' ');expect(()=>f.store.apply(e)).toThrow('已变化');expect(()=>f.store.remove(e)).toThrow('已变化');expect(f.values.has(e.key)).toBe(true) })
 it('deleting one record leaves other presets and user data intact', () => { const f=fixture();f.store.save('first',base());f.store.save('second',base());f.values.set('note','safe');const e=f.store.list().entries[0];f.store.remove(e);expect(f.store.list().entries).toHaveLength(1);expect(f.values.get('note')).toBe('safe') })
 it('cannot delete arbitrary non-preset keys', () => { const f=fixture();f.values.set('theme','dark');expect(()=>f.store.remove({key:'theme',raw:'dark'})).toThrow();expect(f.values.get('theme')).toBe('dark') })
 it('failure deleting preserves the record', () => { const f=fixture();f.store.save('x',base());f.storage.removeItem=()=>{throw Error('denied')};expect(()=>f.store.remove(f.store.list().entries[0])).toThrow('删除失败');expect(f.values.size).toBe(1) })
 it('a throwing observer cannot turn a completed write into a reported failure', () => { const f=fixture();f.store.subscribe(()=>{throw Error('view')});expect(()=>f.store.save('x',base())).not.toThrow();expect(f.values.size).toBe(1) })
 it('unsubscribes and announces only successful mutations', () => { const f=fixture(), listener=vi.fn();const off=f.store.subscribe(listener);f.store.save('x',base());expect(listener).toHaveBeenCalledTimes(1);off();f.store.save('y',base());expect(listener).toHaveBeenCalledTimes(1) })
})
