import React, { act, StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { beforeEach, afterEach, expect, it, vi } from 'vitest'
import Panel from './S3LocalOverviewPanel.jsx'
import { localOverviewSuccess } from '../../scripts/s3-local-overview-binding-cases.mjs'
let host,root,native,previous
const flush=async()=>{for(let i=0;i<10;i++)await Promise.resolve()}
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve}}
const render=props=>act(async()=>root.render(<StrictMode><Panel {...props}/></StrictMode>))
const button=label=>[...host.querySelectorAll('button')].find(b=>b.textContent===label)
const click=label=>act(async()=>{button(label).click();await flush()})
beforeEach(()=>{vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);previous=Object.getOwnPropertyDescriptor(window,'electronAPI');native=vi.fn(async()=>localOverviewSuccess());Object.defineProperty(window,'electronAPI',{configurable:true,value:{s3LocalOverviewRead:native}});host=document.createElement('div');document.body.append(host);root=createRoot(host)})
afterEach(async()=>{await act(async()=>root.unmount());host.remove();if(previous)Object.defineProperty(window,'electronAPI',previous);else delete window.electronAPI;vi.useRealTimers();vi.restoreAllMocks();vi.unstubAllGlobals()})
it('local inventory panel does not scan on mount or StrictMode replay',async()=>{await render();expect(native).not.toHaveBeenCalled();expect(host.querySelector('h3').textContent).toBe('本地只读盘点');expect(host.querySelector('table')).toBeNull()})
it('local inventory panel explicit read displays canonical counts not file size or sync success',async()=>{await render();await click('读取本地统计');expect(native).toHaveBeenCalledTimes(1);expect(native).toHaveBeenCalledWith({readOnly:true});expect(host.querySelectorAll('tbody tr').length).toBe(4);expect(host.textContent).toContain('本次盘点已完成');expect(host.textContent).toContain('不是数据库文件大小');expect(host.textContent).toContain('不代表原子快照')})
it('local inventory panel uses table headers and status semantics',async()=>{await render();await click('读取本地统计');expect(host.querySelector('section').getAttribute('aria-labelledby')).toBe(host.querySelector('h3').id);expect(host.querySelector('[role=status]').getAttribute('aria-live')).toBe('polite');expect(host.querySelectorAll('th[scope=row]').length).toBe(4);expect(host.querySelector('caption')).not.toBeNull()})
it('local inventory panel cannot start duplicates while pending',async()=>{const d=deferred();native.mockReturnValue(d.promise);await render();await click('读取本地统计');expect(button('正在读取…').disabled).toBe(true);await click('正在读取…');expect(native).toHaveBeenCalledTimes(1);await act(async()=>{d.resolve(localOverviewSuccess());await flush()})})
it('local inventory panel stop discards late counts without claiming native cancellation',async()=>{const d=deferred();native.mockReturnValue(d.promise);await render();await click('读取本地统计');await click('停止采用本次结果');expect(host.textContent).toContain('不代表原生读取已经取消');await act(async()=>{d.resolve(localOverviewSuccess());await flush()});expect(host.querySelector('table')).toBeNull()})
it('local inventory panel explains occupied native slot after stopped wait',async()=>{const d=deferred();native.mockReturnValue(d.promise);await render();await click('读取本地统计');await click('停止采用本次结果');await click('读取本地统计');expect(native).toHaveBeenCalledTimes(1);expect(host.textContent).toContain('上一次读取仍在收尾');await act(async()=>{d.resolve(localOverviewSuccess());await flush()})})
it('local inventory panel missing native entry fails locally without browser fallback',async()=>{delete window.electronAPI;const fetch=vi.spyOn(globalThis,'fetch');await render();await click('读取本地统计');expect(host.textContent).toContain('没有可用的原生盘点入口');expect(fetch).not.toHaveBeenCalled()})
it('local inventory panel explains whole-inventory refusal and limits',async()=>{native.mockResolvedValue({success:false,status:422,code:'local-overview-not-available',data:null});await render();await click('读取本地统计');expect(host.querySelector('table')).toBeNull();expect(host.textContent).toContain('没有采用部分统计');expect(host.textContent).toContain('128 条数据库记录')})
it('local inventory panel rejects malformed statistics without showing partial data',async()=>{const bad=localOverviewSuccess();bad.data.records=999;native.mockResolvedValue(bad);await render();await click('读取本地统计');expect(host.querySelector('table')).toBeNull();expect(host.textContent).not.toContain('999');expect(host.textContent).toContain('格式或统计无效')})
it('local inventory panel disabled transition revokes a pending result',async()=>{const d=deferred();native.mockReturnValue(d.promise);await render();await click('读取本地统计');await render({disabled:true});await act(async()=>{d.resolve(localOverviewSuccess());await flush()});expect(host.querySelector('table')).toBeNull();expect(button('读取本地统计').disabled).toBe(true)})
it('local inventory panel revision A-B-A never revives stale counts',async()=>{const d=deferred();native.mockReturnValue(d.promise);await render({revision:0});await click('读取本地统计');await render({revision:1});await render({revision:0});await act(async()=>{d.resolve(localOverviewSuccess());await flush()});expect(host.querySelector('table')).toBeNull();expect(native).toHaveBeenCalledTimes(1)})
it('local inventory panel can explicitly refresh but never polls',async()=>{await render();await click('读取本地统计');await click('重新读取统计');await render();expect(native).toHaveBeenCalledTimes(2)})
it('local inventory panel timeout remains a wait timeout after late success',async()=>{vi.useFakeTimers();const d=deferred();native.mockReturnValue(d.promise);await render();await click('读取本地统计');await act(async()=>{vi.advanceTimersByTime(10000);await flush()});expect(host.textContent).toContain('等待盘点超时');await act(async()=>{d.resolve(localOverviewSuccess());await flush()});expect(host.querySelector('table')).toBeNull()})
it('local inventory panel zero counts still distinguish empty observation from sync consent',async()=>{const empty=localOverviewSuccess();Object.assign(empty.data,{records:0,record_bytes:0,attachment_bytes:0,base_items:0});empty.data.kinds.forEach(k=>Object.assign(k,{records:0,record_bytes:0}));native.mockResolvedValue(empty);await render();await click('读取本地统计');expect(host.querySelector('table')).not.toBeNull();expect(host.textContent).toContain('写入授权');expect(host.textContent).not.toContain('同步完成。')})
